CREATE TABLE PUBLIC.CARGO (
	ID VARCHAR(100) NOT NULL,
	CARGO_TYPE VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	WEIGHT BIGINT NOT NULL,
	"SIZE" VARCHAR(100),
	MATERIAL VARCHAR(100),
	EXPIRATION_DATE DATE,
	STORE_TEMPERATURE BIGINT,
	CONSTRAINT CARGO_PK PRIMARY KEY (ID)
);
CREATE INDEX CARGO_ID_IDX ON PUBLIC.CARGO (ID,CARGO_TYPE,NAME,WEIGHT,"SIZE",MATERIAL,EXPIRATION_DATE,STORE_TEMPERATURE);
CREATE UNIQUE INDEX PRIMARY_KEY_3 ON PUBLIC.CARGO (ID);


CREATE TABLE PUBLIC.CARRIER (
	ID VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	ADDRESS VARCHAR(100) NOT NULL,
	CARRIER_TYPE VARCHAR(100) NOT NULL,
	CONSTRAINT CARRIER_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC.CARRIER (ID);



CREATE TABLE PUBLIC.TRANSPORTATION (
	ID_CARGO VARCHAR(100) NOT NULL,
	"ID_CARRIER" VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
	BILL_TO VARCHAR(100) NOT NULL,
	TRANSPORTATION_BEGIN_DATE DATE NOT NULL,
	CONSTRAINT TRANSPORTATION_FK FOREIGN KEY (ID_CARGO) REFERENCES PUBLIC.CARGO(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT TRANSPORTATION_FK_1 FOREIGN KEY ("ID_CARRIER") REFERENCES PUBLIC.CARRIER(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX TRANSPORTATION_FK_1_INDEX_F ON PUBLIC.TRANSPORTATION ("ID_CARRIER");
CREATE INDEX TRANSPORTATION_FK_INDEX_F ON PUBLIC.TRANSPORTATION (ID_CARGO);