INSERT INTO PUBLIC.CARGO (ID,CARGO_TYPE,NAME,WEIGHT,"SIZE",MATERIAL,EXPIRATION_DATE,STORE_TEMPERATURE) VALUES (
'1_a','FOOD','APPLE',100,NULL,NULL,'2020-11-11',-50);
INSERT INTO PUBLIC.CARGO (ID,CARGO_TYPE,NAME,WEIGHT,"SIZE",MATERIAL,EXPIRATION_DATE,STORE_TEMPERATURE) VALUES (
'2_a','CLOTHERS','JEANS',200,'XXL','COTTON',NULL,NULL);
INSERT INTO PUBLIC.CARGO (ID,CARGO_TYPE,NAME,WEIGHT,"SIZE",MATERIAL,EXPIRATION_DATE,STORE_TEMPERATURE) VALUES (
'3_a','FOOD','ORANGE',300,NULL,NULL,'2025-12-20',-20);


INSERT INTO PUBLIC.CARRIER (ID,NAME,ADDRESS,CARRIER_TYPE) VALUES (
'1_b','YOUR_DELIVERY','Spb, Nevskiy 800','SHIP');
INSERT INTO PUBLIC.CARRIER (ID,NAME,ADDRESS,CARRIER_TYPE) VALUES (
'2_b','FASTEST EVER','Sp, Prosveheniya 900','PLANE');


INSERT INTO PUBLIC.TRANSPORTATION (ID_CARGO,"ID_CARRIER",DESCRIPTION,BILL_TO,TRANSPORTATION_BEGIN_DATE) VALUES (
'1_a','1_b','Vip order','Ivanov','2010-11-11');
INSERT INTO PUBLIC.TRANSPORTATION (ID_CARGO,"ID_CARRIER",DESCRIPTION,BILL_TO,TRANSPORTATION_BEGIN_DATE) VALUES (
'2_a','1_b','Fragile','Petrov','2011-11-11');
INSERT INTO PUBLIC.TRANSPORTATION (ID_CARGO,"ID_CARRIER",DESCRIPTION,BILL_TO,TRANSPORTATION_BEGIN_DATE) VALUES (
'3_a','2_b','Fragile','Sidorov','2017-01-01');
